web:
  build: .
  links:
    - mysql
  ports:
    - "8080:80"
  volumes:
      - ./src/:/var/www/html
mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: myapp
